[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.5

[font.bold]
family = "Iosevka"

[font.bold_italic]
family = "Iosevka"

[font.italic]
family = "Iosevka"

[font.normal]
family = "Iosevka"
style = "Medium"

[shell]
program = "/bin/zsh"
