vim.g.vimtex_view_method = 'zathura'
vim.g.gruvbox_material_foreground = 'material'
vim.g.gruvbox_material_background = 'medium'
vim.g.gruvbox_material_diagnostic_text_highlight = true
vim.g.gruvbox_material_diagnostic_line_highlight = true
vim.g.gruvbox_material_enable_italic = true
vim.g.sonokai_style = 'shusia'
vim.g.sonokai_enable_italic = true
vim.g.everforest_background = 'hard'
vim.g.material_style = 'darker'
vim.g.adwaita_darker = false -- for darker version
vim.g.adwaita_disable_cursorline = false -- to disable cursorline
vim.g.adwaita_transparent = false -- makes the background transparent
vim.g.shfmt_opt= '-ci'
vim.g.adwaita_darker = true
