theme = "gruvbox"

[editor]
line-number = "relative"
scroll-lines = 1
auto-save = false
mouse = false
cursorline = true
true-color = true
color-modes = true
auto-pairs = true
rulers = [80, 120]
idle-timeout = 50
# completion-trigger-len = 1

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[keys.normal]
# H = "extend_char_left"
# L = "extend_char_right"
# J = "extend_line_down"
# K = "extend_line_up"

# F = "extend_prev_char"
# X = "extend_line_above"
# B = "extend_prev_word_start"
# W = "extend_next_word_start"
# E = "extend_next_word_end"

# F/H are now extend versions of f/t; so remap them to alt
# A-f = "find_prev_char"
# A-h = "till_prev_char"
# A-F = "extend_prev_char"
# A-H = "extend_till_prev_char"
# space.g.f = "find_prev_char"
# space.g.h = "till_prev_char"
# space.g.F = "extend_prev_char"
# space.g.H = "extend_till_prev_char"

# g.h = "goto_line_start"
g.s = "goto_file_start"
g.e = "goto_file_end"
# g.r = "goto_line_end"
g.i = "goto_first_nonwhitespace"
# g.h = "no_op"
# g.l = "no_op"
# g.D = "goto_reference"
# G.H = "extend_to_line_start"
# G.I = "extend_to_first_nonwhitespace"
# G.L = "extend_to_line_end"

C-k = "split_selection_on_newline"

# flip anchor and cursor
space.space = "flip_selections"

C-e = "scroll_down"
C-y = "scroll_up"

# space.c = "toggle_comments"
# space.w.c = "jump_view_left"
# space.w.r = "jump_view_right"
# space.w.t = "jump_view_down"
# space.w.s = "jump_view_up"
# space.w.o = "hsplit"

A-f = "flip_selections"

[keys.select]
g.s = "goto_file_start"
# c = "extend_char_left"
# r = "extend_char_right"
# t = "extend_line_down"
# s = "extend_line_up"
# g.h = "goto_line_start"
# g.l = "goto_line_end"
# g.h = "no_op"
# g.l = "no_op"
# "é" = "move_next_word_start"
# "É" = "move_next_long_word_start"
# h = "replace"
# H = "replace_with_yanked"
# l = "change_selection"
# "è" = "split_selection"
# "à" = "find_till_char"
S = "select_regex"
# z = "split_selection"
X = "extend_line_above"

# [keys.insert]
# " " = ["collapse_selection", ":insert-output printf ' '", "move_char_right"]

A-f = "flip_selections"
