[[language]]
name = "c"
indent = { tab-width = 8, unit = "        " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
file-types = ["md", "rmd"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
